### ISSUE TITLE
Error running through GCP Project Setup

### ISSUE THREAD

**Issue by mcantrell** [kubeflow/website#2121]
https://www.kubeflow.org/docs/gke/deploy/project-setup/

> 7 Initialize your project to ready it for Anthos Service Mesh installation.

```
curl --request POST \
  --header "Authorization: Bearer $(gcloud auth print-access-token)" \
  --data '' \
  https://meshconfig.googleapis.com/v1alpha1/projects/${PROJECT_ID}:initialize
```

> Refer to Anthos Service Mesh documentation for details.
> You do not need a running GKE cluster. The deployment process creates a cluster for you.

Executing this step generates the following error:

```
{
  "error": {
    "code": 400,
    "message": "Workload Identity Pool does not exist (project-xxx.svc.id.goog).",
    "status": "INVALID_ARGUMENT"
  }
}
```

I've verified that the project exists and the meshconfig api is enabled for it.

**Comment by mcantrell** [comment]
Creating a temporary cluster seems to make the error go away.

```
gcloud beta container clusters create tmp-cluster \
  --release-channel regular \
  --workload-pool=${PROJECT_ID}.svc.id.goog

gcloud beta container clusters delete tmp-cluster
```

I'm just dipping my toes into the anthos water here so I'm not entirely sure if this expected 🤷

**Comment by 8bitmp3** [comment]
Cheers@mcantrell!Do you think we can improve the steps (maybe add a "Note" pointing to your workaround)?

Btw, @Bobgy is with GCP. 

/assign @Bobgy @8bitmp3

**Comment by ryo-matsuzaka** [comment]
Thank you for sharing @mcantrell 
I need a little bit modified like this.
```
gcloud beta container clusters create tmp-cluster \
  --release-channel regular \
  --workload-pool=${PROJECT_ID}.svc.id.goog \
  --zone=asia-northeast1-a
```
I add zone.

After tun the code, I was able to finish the step 7"Initialize your project to ready it for Anthos Service Mesh installation."

**Comment by Bobgy** [comment]
I'll try to follow up on the issue

**Comment by closerforever** [comment]
> Thank you for sharing @mcantrell
> I need a little bit modified like this.
> 
> ```
> gcloud beta container clusters create tmp-cluster \
>   --release-channel regular \
>   --workload-pool=${PROJECT_ID}.svc.id.goog \
>   --zone=asia-northeast1-a
> ```
> 
> I add zone.
> 
> After run the code, I was able to finish the step 7"Initialize your project to ready it for Anthos Service Mesh installation."

somehow, I successfully created a cluster per your code; I am still not able to finish the step 7; it gave me an error, like this:
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/ro
bot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{
background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelog
o_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.c
om/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/v1alpha1/projects/:initialize</code> was not found on this server.  <ins>That’s all we know.</ins>

**Comment by Bobgy** [comment]
/assign @jlewi 
Can you take a look at the above comment?
I remember you found some change in the setup process.

**Comment by theofpa** [comment]
> The requested URL `/v1alpha1/projects/:initialize` was not found on this server. That’s all we know.

@closerforever seems like your `$PROJECT_ID` is empty, the address should be `/v1alpha1/projects/yourproject_12345938593845.svc.id.goog:initialize`, so make sure you have that variable configured using:

```
export PROJECT_ID=yourproject_12345938593845
```

**Comment by SaschaHeyer** [comment]
Will this be solved at some point? Having errors basically in the first setup step should be avoided.

**Comment by Bobgy** [comment]
Agree, let's keep this open

**Comment by Bobgy** [comment]
Let's track fixing the problem in code repo, not documentation repo: https://github.com/kubeflow/gcp-blueprints/issues/189

**Comment by charlescurt** [comment]
This error is still here. Is newer documentation I am unaware of?
